#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosDerecho.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ActivosDerecho")]
	public partial class ModeloDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertActivo(Activo instance);
    partial void UpdateActivo(Activo instance);
    partial void DeleteActivo(Activo instance);
    partial void InsertContrasena(Contrasena instance);
    partial void UpdateContrasena(Contrasena instance);
    partial void DeleteContrasena(Contrasena instance);
    #endregion
		
		public ModeloDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ActivosDerechoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Activo> Activos
		{
			get
			{
				return this.GetTable<Activo>();
			}
		}
		
		public System.Data.Linq.Table<Contrasena> Contrasenas
		{
			get
			{
				return this.GetTable<Contrasena>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Activos")]
	public partial class Activo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private int _placa;
		
		private string _nombreDescripcion;
		
		private string _espacioFisico;
		
		private string _encargado;
		
		private int _estado;
		
		private string _inventarioPor;
		
		private string _conciliacion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnplacaChanging(int value);
    partial void OnplacaChanged();
    partial void OnnombreDescripcionChanging(string value);
    partial void OnnombreDescripcionChanged();
    partial void OnespacioFisicoChanging(string value);
    partial void OnespacioFisicoChanged();
    partial void OnencargadoChanging(string value);
    partial void OnencargadoChanged();
    partial void OnestadoChanging(int value);
    partial void OnestadoChanged();
    partial void OninventarioPorChanging(string value);
    partial void OninventarioPorChanged();
    partial void OnconciliacionChanging(string value);
    partial void OnconciliacionChanged();
    #endregion
		
		public Activo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa", DbType="Int NOT NULL")]
		public int placa
		{
			get
			{
				return this._placa;
			}
			set
			{
				if ((this._placa != value))
				{
					this.OnplacaChanging(value);
					this.SendPropertyChanging();
					this._placa = value;
					this.SendPropertyChanged("placa");
					this.OnplacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreDescripcion", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string nombreDescripcion
		{
			get
			{
				return this._nombreDescripcion;
			}
			set
			{
				if ((this._nombreDescripcion != value))
				{
					this.OnnombreDescripcionChanging(value);
					this.SendPropertyChanging();
					this._nombreDescripcion = value;
					this.SendPropertyChanged("nombreDescripcion");
					this.OnnombreDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_espacioFisico", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string espacioFisico
		{
			get
			{
				return this._espacioFisico;
			}
			set
			{
				if ((this._espacioFisico != value))
				{
					this.OnespacioFisicoChanging(value);
					this.SendPropertyChanging();
					this._espacioFisico = value;
					this.SendPropertyChanged("espacioFisico");
					this.OnespacioFisicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_encargado", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string encargado
		{
			get
			{
				return this._encargado;
			}
			set
			{
				if ((this._encargado != value))
				{
					this.OnencargadoChanging(value);
					this.SendPropertyChanging();
					this._encargado = value;
					this.SendPropertyChanged("encargado");
					this.OnencargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Int NOT NULL")]
		public int estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inventarioPor", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string inventarioPor
		{
			get
			{
				return this._inventarioPor;
			}
			set
			{
				if ((this._inventarioPor != value))
				{
					this.OninventarioPorChanging(value);
					this.SendPropertyChanging();
					this._inventarioPor = value;
					this.SendPropertyChanged("inventarioPor");
					this.OninventarioPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conciliacion", DbType="VarChar(MAX)")]
		public string conciliacion
		{
			get
			{
				return this._conciliacion;
			}
			set
			{
				if ((this._conciliacion != value))
				{
					this.OnconciliacionChanging(value);
					this.SendPropertyChanging();
					this._conciliacion = value;
					this.SendPropertyChanged("conciliacion");
					this.OnconciliacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contrasenas")]
	public partial class Contrasena : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _usuario;
		
		private string _passUsuario;
		
		private string _correo;
		
		private string _passCorreo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnpassUsuarioChanging(string value);
    partial void OnpassUsuarioChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnpassCorreoChanging(string value);
    partial void OnpassCorreoChanged();
    #endregion
		
		public Contrasena()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passUsuario", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string passUsuario
		{
			get
			{
				return this._passUsuario;
			}
			set
			{
				if ((this._passUsuario != value))
				{
					this.OnpassUsuarioChanging(value);
					this.SendPropertyChanging();
					this._passUsuario = value;
					this.SendPropertyChanged("passUsuario");
					this.OnpassUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passCorreo", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string passCorreo
		{
			get
			{
				return this._passCorreo;
			}
			set
			{
				if ((this._passCorreo != value))
				{
					this.OnpassCorreoChanging(value);
					this.SendPropertyChanging();
					this._passCorreo = value;
					this.SendPropertyChanged("passCorreo");
					this.OnpassCorreoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
