<?xml version="1.0" encoding="utf-8"?><Database Name="ActivosDerecho" Class="ModeloDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Munich\SQLEXPRESS;Initial Catalog=ActivosDerecho;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ActivosDerechoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Activos" Member="Activos">
    <Type Name="Activo">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="placa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreDescripcion" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="espacioFisico" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="encargado" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="inventarioPor" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="conciliacion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contrasenas" Member="Contrasenas">
    <Type Name="Contrasena">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="passUsuario" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="passCorreo" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>